services:
  - type: web
    name: quote-speak-app
    runtime: python3
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 wsgi:application
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: MAX_TEXT_LENGTH
        value: 2000
      - key: MAX_TITLE_LENGTH
        value: 100